version: '3.4'

services:
  
  server:
    image: openttd.server
    container_name: tg.server
    networks:
      - tg
    build:
      context: .
      dockerfile: OpenTTD/Dockerfile
  
  db:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    container_name: tg.db
    networks:
      - tg
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"

  seq:
    image: datalust/seq:latest
    container_name: tg.seq
    networks:
      - tg
    environment:
      ACCEPT_EULA: "Y"

networks:
  tg:
    name: tg.network
