version: '3.4'

services:
  server:
    ports:
      - "3982:3982/tcp"
      - "3982:3982/udp"
      - "3977:3977/tcp"
        
  redis:
    ports:
      - '6379:6379'
      
  seq:
    ports:
      - "5341:80"
        
  postgres:
    ports:
      - "5432:5432"