version: '3.4'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    container_name: tg.db
    networks:
      - tg
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"

  seq:
    image: datalust/seq:latest
    container_name: tg.seq
    networks:
      - tg
    environment:
      ACCEPT_EULA: "Y"

  openttd.admin.client:
    image: openttd.admin.client
    container_name: tg.openttd.admin.client
    networks:
      - tg
    depends_on:
      - db
      - seq
    build: 
      context: .
      dockerfile: Services/OpenTTD/OpenTTD.AdminClient/Dockerfile

  openttd.api:
    image: openttd.api
    container_name: tg.openttd.api
    networks:
      - tg
    depends_on:
      - openttd.admin.client
    build:
      context: .
      dockerfile: Services/OpenTTD/OpenTTD.API/Dockerfile

  admin.server:
    image: admin.server
    container_name: tg.admin.server
    networks:
      - tg
    depends_on:
      - openttd.api
    build:
      context: .
      dockerfile: WebApps/Admin/Admin.Server/Dockerfile

  admin.client:
    image: admin.client
    container_name: tg.admin.client
    networks:
      - tg
    depends_on:
      - admin.server
    build:
      context: .
      dockerfile: WebApps/Admin/Admin.Client/Dockerfile


networks:
  tg:
    name: tg.network