version: "3.8"

name: "betterttd"

services:
        
  server:
    image: openttd.server
    container_name: bttd.server
    networks:
      - tg
    build:
      context: .
      dockerfile: Services/OpenTTD/Dockerfile
  
  redis:
    image: arm64v8/redis
    container_name: bttd.redis  
    networks:
      - tg

  seq:
    image: datalust/seq:latest
    container_name: bttd.seq
    networks:
      - tg
    environment:
      ACCEPT_EULA: "Y"
  
  postgres:
    image: postgres:14.3-alpine
    container_name: bttd.postgres
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - tg

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: bttd.rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=sa
      - RABBITMQ_DEFAULT_PASS=p@ssw0rd
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - tg
        
networks:
  tg:
    name: bttd.network
