version: "3.8"

name: "betterttd"

services:
        
  server:
    image: openttd.server
    container_name: bttd.server
    networks:
      - tg
    build:
      context: .
      dockerfile: Services/OpenTTD/Dockerfile
  
  redis:
    image: arm64v8/redis
    container_name: bttd.redis  
    networks:
      - tg

  seq:
    image: datalust/seq:latest
    container_name: bttd.seq
    networks:
      - tg
    environment:
      ACCEPT_EULA: "Y"
  
networks:
  tg:
    name: bttd.network
