version: '3.4'

services:
  server:
    ports:
      - "3982:3982/tcp"
      - "3982:3982/udp"
      - "3977:3977/tcp"
        
  db:
    ports:
      - "1433:1433"
  
  seq:
    ports:
      - "5341:80"
  
  redis:
    ports:
      - '6379:6379'